name: Build

on:
  push:
    branches: [redesign]
  pull_request:
    branches: [redesign]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-latest

    env:
      Solution_Name: Unicord.sln
      Project_Name: Unicord.Universal.Package
      Project_Name_2: Unicord.Universal
      ProjectFile_Name: Unicord.Universal.Package/Unicord.Universal.Package.wapproj
      BackgroundProjectFile_Name: Unicord.Universal.Background/Unicord.Universal.Background.csproj

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      # Add MSBuild to the PATH
      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v2

      # Restore NuGet packages
      - name: Restore NuGet Packages
        run: |
          msbuild $env:Solution_Name /t:Restore /p:Configuration=$env:Configuration /p:RuntimeIdentifier=win-x86
          msbuild $env:Solution_Name /t:Restore /p:Configuration=$env:Configuration /p:RuntimeIdentifier=win-x64
          msbuild $env:Solution_Name /t:Restore /p:Configuration=$env:Configuration /p:RuntimeIdentifier=win-arm
        env:
          Configuration: ${{ matrix.configuration }}

      # Decode the base64 encoded PFX and save certificate
      - name: Load Certificate
        run: |
          $pfx_cert_byte = [System.Convert]::FromBase64String("${{ secrets.BASE64_ENCODED_PFX }}")
          $certificatePath = "GitHubActionsWorkflow.pfx"
          [IO.File]::WriteAllBytes("$env:Project_Name/$certificatePath", $pfx_cert_byte)
          [IO.File]::WriteAllBytes("$env:Project_Name_2/$certificatePath", $pfx_cert_byte)

      # Adjust package version dynamically
      - name: Adjust Package Version
        run: |
          $epoch = (Get-Date) - ([System.DateTime]::new(2024, 11, 01))
          $file = (Resolve-Path "Unicord.Universal.Package/Package.appxmanifest")
          $xml = [System.Xml.XmlDocument]::new()
          $xml.Load($file)
          $node = $xml.GetElementsByTagName("Identity", "http://schemas.microsoft.com/appx/manifest/foundation/windows10")[0]
          $version = [System.Version]::Parse($node.GetAttribute("Version"))
          $version = [System.Version]::new($version.Major, $version.Minor, $version.Build, $epoch.TotalMinutes);
          $node.SetAttribute("Version", $version.ToString())
          $xml.Save($file)

      # Install UWP Workload
      - name: Install Visual Studio UWP Workload
        run: |
          choco install visualstudio2022-workload-universal --yes --limit-output
        shell: powershell

      # Build App Packages
      - name: Build App Packages
        run: |
          msbuild $env:ProjectFile_Name `
            /p:Configuration=$env:Configuration `
            /p:AppxBundle=Always `
            /p:AppxBundlePlatforms="x86|x64|ARM" `
            /p:AppxPackageSigningEnabled=true
        env:
          Configuration: ${{ matrix.configuration }}

      # Remove the PFX for safety
      - name: Cleanup
        run: Remove-Item -Path Unicord.Universal.Package/GitHubActionsWorkflow.pfx -Force

      # Upload the MSIX package as artifact
      - name: Upload Appx Package
        uses: actions/upload-artifact@v4
        with:
          name: AppxPackage-${{ matrix.configuration }}
          path: ${{ env.Project_Name }}\Packages
